#!/bin/bash

set -e

echo "Warning: by running this command all local resources generated by terraform will be removed. This won't affect anything in Azure."
echo -n "Confirm cleanup? [y/N]"
read -n 1 confirm

echo
if [[ $confirm != "y" ]]; then
    echo "Aborting"
    exit 1
fi

echo "Removing..."
cd $(dirname $(readlink -f $0))
find .. -name .terraform | xargs rm -rvf
find .. -name terraform.tfstate.d | xargs rm -rvf
find .. -name backend-provider.tf | xargs rm -rvf
find .. -name terraform.tfstate | xargs rm -rvf
find .. -name terraform.tfstate.backup | xargs rm -rvf
rm -rvf ../config/out

