name: elasticsearch
home: https://www.elastic.co/products/elasticsearch
version: 1.4.0
appVersion: 6.3.1
description: Flexible and powerful open source, distributed real-time search and analytics
  engine.
icon: https://static-www.elastic.co/assets/blteb1c97719574938d/logo-elastic-elasticsearch-lt.svg
sources:
- https://www.elastic.co/products/elasticsearch
- https://github.com/clockworksoul/helm-elasticsearch
- https://github.com/pires/kubernetes-elasticsearch-cluster